### ISSUE TITLE
`serde` feature

### ISSUE THREAD

**Issue by nazar-pc** [KokaKiwi/rust-hex#90]
Right now `serde` is sort of exposed like a feature simply due to `serde` being an optional dependency, but `hex/serde` is not in fact sufficient to enable it properly, `alloc` feature is also required, which for some reason isn't even shown on docs.rs (it only shows that `serde` feature is required).

It'd be less error-prone if `serde` was added as an explicit feature instead:
```toml
serde = [
    "dep:serde",
    "alloc",
]
```

**Comment by rossmacarthur** [comment]
Hi, I looked into this but this is not always true, `alloc` is not required for the deserialization implementation.

**Cargo.toml**

```toml
[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
hex = { version = "0.4", default-features = false, features = ["serde"] }
```

**main.rs**
```rust
#![no_std]

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Foo {
    #[serde(with = "hex")]
    bar: [u8; 3],
}
```

I PRed a change to fix the documentation feature labels https://github.com/KokaKiwi/rust-hex/pull/91
